version: '3'
services:

  app:
    build: ./app
    container_name: app
    ports:
      - "80:3000"
      - "443:443"
    restart: always
    volumes:
      - certbot-webroot-flamov:/app/public/.well-known
      - certbot-letsencrypt:/etc/letsencrypt

  certbot:
    build: ./certbot
    container_name: certbot
    restart: always
    volumes:
      - certbot-webroot-flamov:/webroots/flamov.com/.well-known
      - certbot-letsencrypt:/etc/letsencrypt

volumes:
  certbot-webroot-flamov:
  certbot-letsencrypt:
