name: Build and deploy test

on:
  push:
    branches:
      - feature/redesign

jobs:
  build-deploy-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build and push Docker image
      uses: docker/build-push-action@v1
      with:
        username: Flamov
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        repository: flamov/portfolio/portfolio
        tag_with_sha: true
        tags: test
