name: Deploy test

on:
  workflow_dispatch:
  push:
    branches:
      - feature/redesign

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        run: echo ${{ secrets.PACKAGES_TOKEN }} | docker login ghcr.io -u Flamov --password-stdin

      - name: Build Docker image
        run: docker build . -t ghcr.io/flamov/portfolio:test

      - name: Push Docker image to GitHub Container Registry
        run: docker push ghcr.io/flamov/portfolio:test

  deploy-test:
    needs: build-test

    environment:
      name: test
      url: https://test.flamov.com

    runs-on: ubuntu-latest

    steps:
      - name: Deploy test image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script_stop: true
          script: |
            cd flamov-portfolio-compose
            echo ${{ secrets.PACKAGES_TOKEN }} | docker login ghcr.io -u Flamov --password-stdin
            docker-compose pull app-test
            docker-compose up --no-deps -d app-test
